"""Public declarations for the Agent loop and Tool runtime plugins."""

from XBotv2.agentloop.contracts import (
    DEFAULT_MAX_ITERATIONS,
    AgentLoopDriverPort,
    AgentLoopFactoryPort,
    AllTools,
    LoopFactoryOptions,
    LoopState,
    LIST_TOOLS,
    ToolCatalog,
    ToolDescription,
    ToolRegistration,
    ToolGuard,
    ToolSelection,
    ToolsPort,
    InboxItem,
    InboxSink,
    InboxChange,
    InboxTarget,
    Inserted,
    Edited,
    Removed,
    Retargeted,
    Claimed,
    Consumed,
    Discarded,
    HumanInput,
    RuntimeInput,
)
from XBotv2.agentloop.events import (
    EventPort,
    Events,
    SHORT_CIRCUIT_EVENTS,
)
from XBotv2.agentloop.inbox import AgentInbox, EphemeralInboxSink
from XBotv2.agentloop.protocol import (
    LoopEvent,
    ToolInfo,
    ToolListResponse,
)
__all__ = [
    "AgentInbox",
    "EphemeralInboxSink",
    "AgentLoopDriverPort",
    "AgentLoopFactoryPort",
    "AllTools",
    "DEFAULT_MAX_ITERATIONS",
    "EventPort",
    "InboxItem",
    "InboxSink",
    "InboxChange",
    "InboxTarget",
    "Inserted",
    "Edited",
    "Removed",
    "Retargeted",
    "Claimed",
    "Consumed",
    "Discarded",
    "HumanInput",
    "RuntimeInput",
    "Events",
    "LoopEvent",
    "LoopFactoryOptions",
    "LoopState",
    "LIST_TOOLS",
    "ToolGuard",
    "ToolCatalog",
    "ToolDescription",
    "ToolInfo",
    "ToolListResponse",
    "ToolRegistration",
    "ToolSelection",
    "ToolsPort",
    "SHORT_CIRCUIT_EVENTS",
]
