"""Tests for the JSONL protocol layer."""

import json

from xbotv2.protocol.frames import (
    ProtocolFrame,
    ProtocolEncoder,
    PROTOCOL_VERSION,
    frame_from_json,
)


class TestProtocolFrame:
    """ProtocolFrame serialization."""

    def test_frame_creation(self):
        """Create a basic frame."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="hello_ok",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
            payload={"server_name": "xbotv2"},
        )
        assert frame.protocol_version == PROTOCOL_VERSION
        assert frame.type == "hello_ok"
        assert frame.seq == 1

    def test_to_json_line(self):
        """Frame serializes to valid JSONL."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="test",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
        )
        line = frame.to_json_line()
        assert line.endswith("\n")
        parsed = json.loads(line)
        assert parsed["type"] == "test"
        assert parsed["session_id"] == "s1"

    def test_frame_from_json(self):
        """Deserialization round-trips."""
        frame = ProtocolFrame(
            seq=1,
            direction="client_to_server",
            type="user.message",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
            payload={"content": "hello"},
        )
        line = frame.to_json_line()
        restored = frame_from_json(line)
        assert restored.type == "user.message"
        assert restored.payload["content"] == "hello"

    def test_frame_id_autogenerated(self):
        """frame_id is auto-generated if not provided."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="test",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
        )
        assert frame.frame_id.startswith("frame_")

    def test_ts_autogenerated(self):
        """ts is auto-generated."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="test",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
        )
        assert frame.ts  # Should be an ISO timestamp


class TestProtocolEncoder:
    """ProtocolEncoder maps internal events to wire frames."""

    def test_encoder_sequences(self):
        """Encoder increments seq with each frame."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        f1 = encoder.encode("test1", {"key": "val1"})
        f2 = encoder.encode("test2", {"key": "val2"})
        assert f1.seq == 1
        assert f2.seq == 2

    def test_encode_turn_started(self):
        """Convenience method works."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        frame = encoder.encode_turn_started(5)
        assert frame.type == "turn_started"
        assert frame.payload["turn"] == 5

    def test_encode_assistant_message(self):
        """Assistant message encoding."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        frame = encoder.encode_assistant_message("Hello!", [{"name": "shell", "args": {}}])
        assert frame.type == "assistant_message"
        assert frame.payload["content"] == "Hello!"
        assert len(frame.payload["tool_calls"]) == 1

    def test_encode_error(self):
        """Error encoding."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        frame = encoder.encode_error("Something went wrong", "test_error")
        assert frame.type == "error"
        assert frame.payload["code"] == "test_error"
        assert "Something went wrong" in frame.payload["message"]

    def test_session_id_in_all_frames(self):
        """All frames carry session/thread IDs."""
        encoder = ProtocolEncoder(session_id="my-session", thread_id="my-thread")
        frame = encoder.encode("test", {})
        assert frame.session_id == "my-session"
        assert frame.thread_id == "my-thread"


class TestProviderConfig:
    """LLM client factory tests."""

    def test_create_llm_from_dict_deepseek(self):
        """DeepSeek provider config creates OpenAI client."""
        from xbotv2.llm.client import create_llm

        config = {
            "provider": "deepseek",
            "model": "deepseek-chat",
            "base_url": "https://api.deepseek.com/v1",
            "api_key": "test-key",
            "temperature": 0.7,
            "max_tokens": 8192,
        }
        llm = create_llm(config)
        assert llm is not None
        assert hasattr(llm, "model_name")
        assert llm.model_name == "deepseek-chat"

    def test_create_llm_from_dict_lmstudio(self):
        """LM Studio Anthropic protocol creates Anthropic client."""
        from xbotv2.llm.client import create_llm

        config = {
            "provider": "lmstudio",
            "model": "qwen2.5-coder-7b-instruct",
            "base_url": "http://localhost:1234/v1",
            "api_key": "lm-studio",
            "temperature": 0.7,
            "max_tokens": 4096,
        }
        llm = create_llm(config)
        assert llm is not None
        # ChatAnthropic uses `model` attribute, ChatOpenAI uses `model_name`
        model = getattr(llm, "model_name", None) or getattr(llm, "model", "")
        assert "qwen" in model.lower()

    def test_create_llm_env_var_expansion(self, monkeypatch):
        """Env vars in config are expanded."""
        from xbotv2.llm.client import create_llm

        monkeypatch.setenv("TEST_KEY", "expanded-key")

        config = {
            "provider": "openai",
            "model": "gpt-4",
            "api_key": "${TEST_KEY}",
        }
        llm = create_llm(config)
        # The API key should have been expanded
        assert llm is not None

    def test_create_mock_llm(self):
        """Mock LLM factory works."""
        from xbotv2.llm.client import create_mock_llm

        llm = create_mock_llm([{"content": "test"}])
        assert llm is not None
        assert len(llm.responses) == 1


class TestProviderConfigLoader:
    """Provider config loading from multi-provider YAML — the original bug."""

    def test_selects_named_provider_section(self, tmp_path, monkeypatch):
        """load_provider_config selects the correct YAML section."""
        from xbotv2.config.loader import load_provider_config

        monkeypatch.setenv("TEST_API_KEY", "sk-test-123")

        config_dir = tmp_path / "config"
        config_dir.mkdir(parents=True)
        (config_dir / "provider.yaml").write_text("""
default:
  provider: deepseek
  model: deepseek-chat
  base_url: https://api.deepseek.com/v1
  api_key: ${TEST_API_KEY}

openai:
  provider: openai
  model: gpt-4o
  api_key: sk-openai-xxx
""")

        # Load default → should get deepseek
        c = load_provider_config(config_dir, "default")
        assert c.provider == "deepseek"
        assert c.model == "deepseek-chat"
        assert c.base_url == "https://api.deepseek.com/v1"
        assert c.api_key == "sk-test-123"  # env var expanded

        # Load openai → should get openai section
        c2 = load_provider_config(config_dir, "openai")
        assert c2.provider == "openai"
        assert c2.model == "gpt-4o"
        assert c2.api_key == "sk-openai-xxx"

    def test_env_var_expansion_in_nested_section(self, tmp_path, monkeypatch):
        """${VAR} patterns are expanded in provider sections."""
        from xbotv2.config.loader import load_provider_config

        monkeypatch.setenv("MY_KEY", "expanded-value")

        config_dir = tmp_path / "config"
        config_dir.mkdir(parents=True)
        (config_dir / "provider.yaml").write_text("""
test:
  provider: openai
  model: gpt-4
  api_key: ${MY_KEY}
""")

        c = load_provider_config(config_dir, "test")
        assert c.api_key == "expanded-value"

    def test_missing_env_var_becomes_empty(self, tmp_path):
        """Unset env vars expand to empty string."""
        from xbotv2.config.loader import load_provider_config

        config_dir = tmp_path / "config"
        config_dir.mkdir(parents=True)
        (config_dir / "provider.yaml").write_text("""
test:
  provider: openai
  model: gpt-4
  api_key: ${NONEXISTENT_VAR}
""")

        c = load_provider_config(config_dir, "test")
        assert c.api_key == ""

    def test_fallback_to_default_key(self, tmp_path):
        """Unknown provider_name falls back to 'default' section."""
        from xbotv2.config.loader import load_provider_config

        config_dir = tmp_path / "config"
        config_dir.mkdir(parents=True)
        (config_dir / "provider.yaml").write_text("""
default:
  provider: openai
  model: fallback-model
""")

        c = load_provider_config(config_dir, "nonexistent_provider")
        assert c.provider == "openai"
        assert c.model == "fallback-model"
