"""Tests for the JSONL protocol layer."""

import asyncio
import json
import os
import sys

import pytest
import yaml
from xbotv2.protocol.server import RuntimeServer
from xbotv2.protocol.frames import (
    ProtocolFrame,
    ProtocolEncoder,
    PROTOCOL_VERSION,
    frame_from_json,
)


class TestProtocolFrame:
    """ProtocolFrame serialization."""

    def test_frame_creation(self):
        """Create a basic frame."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="hello_ok",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
            payload={"server_name": "xbotv2"},
        )
        assert frame.protocol_version == PROTOCOL_VERSION
        assert frame.type == "hello_ok"
        assert frame.seq == 1

    def test_to_json_line(self):
        """Frame serializes to valid JSONL."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="test",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
        )
        line = frame.to_json_line()
        assert line.endswith("\n")
        parsed = json.loads(line)
        assert parsed["type"] == "test"
        assert parsed["session_id"] == "s1"

    def test_frame_from_json(self):
        """Deserialization round-trips."""
        frame = ProtocolFrame(
            seq=1,
            direction="client_to_server",
            type="user.message",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
            payload={"content": "hello"},
        )
        line = frame.to_json_line()
        restored = frame_from_json(line)
        assert restored.type == "user.message"
        assert restored.payload["content"] == "hello"

    def test_frame_id_autogenerated(self):
        """frame_id is auto-generated if not provided."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="test",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
        )
        assert frame.frame_id.startswith("frame_")

    def test_ts_autogenerated(self):
        """ts is auto-generated."""
        frame = ProtocolFrame(
            seq=1,
            direction="server_to_client",
            type="test",
            session_id="s1",
            thread_id="t1",
            request_id="r1",
        )
        assert frame.ts  # Should be an ISO timestamp


class TestProtocolEncoder:
    """ProtocolEncoder maps internal events to wire frames."""

    def test_encoder_sequences(self):
        """Encoder increments seq with each frame."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        f1 = encoder.encode("test1", {"key": "val1"})
        f2 = encoder.encode("test2", {"key": "val2"})
        assert f1.seq == 1
        assert f2.seq == 2

    def test_encode_turn_started(self):
        """Convenience method works."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        frame = encoder.encode_turn_started(5)
        assert frame.type == "turn_started"
        assert frame.payload["turn"] == 5

    def test_encode_assistant_message(self):
        """Assistant message encoding."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        frame = encoder.encode_assistant_message("Hello!", [{"name": "shell", "args": {}}])
        assert frame.type == "assistant_message"
        assert frame.payload["content"] == "Hello!"
        assert len(frame.payload["tool_calls"]) == 1

    def test_encode_error(self):
        """Error encoding."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        frame = encoder.encode_error("Something went wrong", "test_error")
        assert frame.type == "error"
        assert frame.payload["code"] == "test_error"
        assert "Something went wrong" in frame.payload["message"]

    def test_session_id_in_all_frames(self):
        """All frames carry session/thread IDs."""
        encoder = ProtocolEncoder(session_id="my-session", thread_id="my-thread")
        frame = encoder.encode("test", {})
        assert frame.session_id == "my-session"
        assert frame.thread_id == "my-thread"

    def test_request_id_in_envelope_not_payload(self):
        """Request correlation stays in the protocol envelope."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")
        frame = encoder.encode_assistant_message("Hello!", request_id="req-123")

        assert frame.request_id == "req-123"
        assert "request_id" not in frame.payload

    def test_encode_usage_accumulates_totals(self):
        """Provider usage is encoded as a first-class protocol frame."""
        encoder = ProtocolEncoder(session_id="s1", thread_id="t1")

        first = encoder.encode_usage(
            {"prompt_tokens": 10, "completion_tokens": 4, "total_tokens": 14},
            request_id="req-1",
        )
        second = encoder.encode_usage(
            {"input_tokens": 3, "output_tokens": 2},
            request_id="req-2",
        )

        assert first.type == "usage"
        assert first.payload["delta"] == {
            "input_tokens": 10,
            "output_tokens": 4,
            "total_tokens": 14,
            "requests": 1,
        }
        assert second.payload["total"] == {
            "input_tokens": 13,
            "output_tokens": 6,
            "total_tokens": 19,
            "requests": 2,
        }


class TestProviderConfig:
    """LLM client factory tests."""

    def test_create_llm_from_dict_deepseek(self):
        """DeepSeek provider config creates OpenAI client."""
        from xbotv2.llm.client import create_llm

        config = {
            "provider": "deepseek",
            "model": "deepseek-chat",
            "base_url": "https://api.deepseek.com/v1",
            "api_key": "test-key",
            "temperature": 0.7,
            "max_tokens": 8192,
        }
        llm = create_llm(config)
        assert llm is not None
        assert hasattr(llm, "model_name")
        assert llm.model_name == "deepseek-chat"

    def test_create_llm_from_dict_lmstudio(self):
        """LM Studio Anthropic protocol creates Anthropic client."""
        from xbotv2.llm.client import create_llm

        config = {
            "provider": "lmstudio",
            "model": "qwen2.5-coder-7b-instruct",
            "base_url": "http://localhost:1234/v1",
            "api_key": "lm-studio",
            "temperature": 0.7,
            "max_tokens": 4096,
        }
        llm = create_llm(config)
        assert llm is not None
        # ChatAnthropic uses `model` attribute, ChatOpenAI uses `model_name`
        model = getattr(llm, "model_name", None) or getattr(llm, "model", "")
        assert "qwen" in model.lower()

    def test_create_llm_env_var_expansion(self, monkeypatch):
        """Env vars in config are expanded."""
        from xbotv2.llm.client import create_llm

        monkeypatch.setenv("TEST_KEY", "expanded-key")

        config = {
            "provider": "openai",
            "model": "gpt-4",
            "api_key": "${TEST_KEY}",
        }
        llm = create_llm(config)
        # The API key should have been expanded
        assert llm is not None

    def test_create_mock_llm(self):
        """Mock LLM factory works."""
        from xbotv2.llm.client import create_mock_llm

        llm = create_mock_llm([{"content": "test"}])
        assert llm is not None
        assert len(llm.responses) == 1

    def test_create_llm_from_mock_provider_config(self):
        """Provider config can select deterministic MockLLM."""
        from xbotv2.llm.client import create_llm
        from xbotv2.llm.mock import MockLLM

        llm = create_llm({
            "provider": "mock",
            "mock_responses": [{"content": "mocked"}],
        })

        assert isinstance(llm, MockLLM)
        assert llm.responses == [{"content": "mocked"}]

    def test_unknown_provider_raises(self):
        """Unknown provider names fail closed instead of silently using OpenAI."""
        from xbotv2.llm.client import create_llm

        with pytest.raises(ValueError, match="Unsupported LLM provider"):
            create_llm({"provider": "not-a-provider", "model": "x"})

    def test_mock_llm_records_input_messages(self):
        """MockLLM call history records the actual request messages."""
        from langchain_core.messages import HumanMessage
        from xbotv2.llm.mock import MockLLM

        llm = MockLLM([{"content": "ok"}])
        response = llm.invoke([HumanMessage(content="hello")])

        assert response.content == "ok"
        assert llm.call_count == 1
        assert [message.content for message in llm.get_call_messages(0)] == ["hello"]

    def test_mock_llm_records_normalized_tool_calls(self):
        """MockLLM call history records normalized tool calls from responses."""
        from langchain_core.messages import HumanMessage
        from xbotv2.llm.mock import MockLLM

        llm = MockLLM([
            {
                "content": "using tool",
                "tool_calls": [{"name": "shell", "args": {"command": "pwd"}, "id": "c1"}],
            }
        ])
        llm.invoke([HumanMessage(content="run")])

        assert llm.verify_tool_call_made("shell")
        assert llm._mock_call_history[0]["tool_calls"] == [
            {
                "name": "shell",
                "args": {"command": "pwd"},
                "id": "c1",
                "type": "tool_call",
            }
        ]


class TestProviderConfigLoader:
    """Provider config loading from multi-provider YAML — the original bug."""

    def test_selects_named_provider_section(self, tmp_path, monkeypatch):
        """load_provider_config selects the correct YAML section."""
        from xbotv2.config.loader import load_provider_config

        monkeypatch.setenv("TEST_API_KEY", "sk-test-123")

        # config_dir is the data root; provider.yaml lives at config_dir/config/
        config_subdir = tmp_path / "config"
        config_subdir.mkdir(parents=True)
        (config_subdir / "provider.yaml").write_text("""
default:
  provider: deepseek
  model: deepseek-chat
  base_url: https://api.deepseek.com/v1
  api_key: ${TEST_API_KEY}

openai:
  provider: openai
  model: gpt-4o
  api_key: sk-openai-xxx
""")

        # Load default → should get deepseek
        c = load_provider_config(tmp_path, "default")
        assert c.provider == "deepseek"
        assert c.model == "deepseek-chat"
        assert c.base_url == "https://api.deepseek.com/v1"
        assert c.api_key == "sk-test-123"  # env var expanded

        # Load openai → should get openai section
        c2 = load_provider_config(tmp_path, "openai")
        assert c2.provider == "openai"
        assert c2.model == "gpt-4o"
        assert c2.api_key == "sk-openai-xxx"

    def test_env_var_expansion_in_nested_section(self, tmp_path, monkeypatch):
        """${VAR} patterns are expanded in provider sections."""
        from xbotv2.config.loader import load_provider_config

        monkeypatch.setenv("MY_KEY", "expanded-value")

        config_subdir = tmp_path / "config"
        config_subdir.mkdir(parents=True)
        (config_subdir / "provider.yaml").write_text("""
test:
  provider: openai
  model: gpt-4
  api_key: ${MY_KEY}
""")

        c = load_provider_config(tmp_path, "test")
        assert c.api_key == "expanded-value"

    def test_missing_env_var_becomes_empty(self, tmp_path):
        """Unset env vars expand to empty string."""
        from xbotv2.config.loader import load_provider_config

        config_subdir = tmp_path / "config"
        config_subdir.mkdir(parents=True)
        (config_subdir / "provider.yaml").write_text("""
test:
  provider: openai
  model: gpt-4
  api_key: ${NONEXISTENT_VAR}
""")

        c = load_provider_config(tmp_path, "test")
        assert c.api_key == ""

    def test_fallback_to_default_key(self, tmp_path):
        """Unknown provider_name falls back to 'default' section."""
        from xbotv2.config.loader import load_provider_config

        config_subdir = tmp_path / "config"
        config_subdir.mkdir(parents=True)
        (config_subdir / "provider.yaml").write_text("""
default:
  provider: openai
  model: fallback-model
""")

        c = load_provider_config(tmp_path, "nonexistent_provider")
        assert c.provider == "openai"
        assert c.model == "fallback-model"


class TestRuntimeServerSubprocess:
    """End-to-end JSONL stdio server roundtrip."""

    @pytest.mark.asyncio
    async def test_server_turn_wait_observes_disconnect_event(self, tmp_path):
        """Connection EOF cancels a running turn even outside live input waits."""
        server = RuntimeServer(data_dir=tmp_path, provider_name="mock", no_plugins=True)
        server._client_frames = asyncio.Queue()
        server._disconnect_event = asyncio.Event()

        async def blocked_turn():
            await asyncio.sleep(60)
            yield {"type": "turn_finished", "data": {"turn": 1}}

        server._disconnect_event.set()

        event = await server._next_turn_event_or_disconnect(blocked_turn())

        assert event is None
        assert server._stop_requested is True

    @pytest.mark.asyncio
    async def test_server_live_interaction_wait_returns_disconnected_on_eof(self, tmp_path):
        """Live ask/permission waits consume the queued EOF sentinel as disconnect."""
        server = RuntimeServer(data_dir=tmp_path, provider_name="mock", no_plugins=True)
        server._client_frames = asyncio.Queue()
        server._disconnect_event = asyncio.Event()
        await server._client_frames.put((None, None))
        server._disconnect_event.set()

        class DummyWriter:
            def write(self, data):
                raise AssertionError("disconnect should not emit an ack")

            async def drain(self):
                raise AssertionError("disconnect should not drain")

        result = await server._wait_for_live_interaction(
            writer=DummyWriter(),
            request_id="user_input:c1",
            client_event={"type": "user_input_required", "data": {}},
            timeout_seconds=None,
        )

        assert result == {
            "request_id": "user_input:c1",
            "status": "disconnected",
            "reason": "client_disconnected",
        }
        assert server._stop_requested is True

    @pytest.mark.asyncio
    async def test_runtime_server_no_plugins_passes_empty_plugin_dirs(
        self, tmp_path, monkeypatch
    ):
        """RuntimeServer no-plugin mode reaches bootstrap, not only CLI args."""
        captured = {}

        class DummyEngine:
            config = type("Config", (), {"agent_name": "Dummy"})()

            async def start_session(self):
                captured["started"] = True

        async def fake_bootstrap(**kwargs):
            captured.update(kwargs)
            return DummyEngine()

        class DummyWriter:
            def __init__(self):
                self.writes = []

            def write(self, data):
                self.writes.append(data)

            async def drain(self):
                captured["drained"] = True

        monkeypatch.setattr("xbotv2.protocol.server.bootstrap", fake_bootstrap)
        server = RuntimeServer(data_dir=tmp_path, provider_name="mock", no_plugins=True)
        hello = ProtocolFrame(
            seq=1,
            direction="client_to_server",
            type="hello",
            session_id="s-core",
            thread_id="t-core",
            request_id="req-hello",
        )
        server._handle_hello(hello)
        writer = DummyWriter()

        response = await server._handle_session_open(
            ProtocolFrame(
                seq=2,
                direction="client_to_server",
                type="session.open",
                session_id="s-core",
                thread_id="t-core",
                request_id="req-open",
            ),
            writer,
        )

        assert response is None
        assert captured["plugin_dirs"] == []
        assert captured["session_id"] == "s-core"
        assert captured["thread_id"] == "t-core"
        assert captured["started"] is True
        assert b"session_ready" in writer.writes[0]

    @pytest.mark.asyncio
    async def test_server_returns_error_for_malformed_json_and_continues(self, tmp_path):
        data_dir = _write_mock_data_dir(tmp_path)
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            proc.stdin.write(b"{not-json}\n")
            await proc.stdin.drain()
            error = await _read_frame(proc)
            assert error.type == "error"
            assert error.payload["code"] == "invalid_frame"

            await _send_frame(
                proc,
                "hello",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-after-invalid",
            )
            hello = await _read_frame(proc)
            assert hello.type == "hello_ok"
            assert hello.request_id == "req-after-invalid"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_returns_error_for_empty_user_message(self, tmp_path):
        data_dir = _write_mock_data_dir(tmp_path)
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _send_frame(
                proc,
                "hello",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-hello",
            )
            assert (await _read_frame(proc)).type == "hello_ok"

            await _send_frame(
                proc,
                "session.open",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-open",
            )
            assert (await _read_frame(proc)).type == "session_ready"

            await _send_frame(
                proc,
                "user.message",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-empty",
                payload={"content": "  "},
            )
            error = await _read_frame(proc)
            assert error.type == "error"
            assert error.request_id == "req-empty"
            assert error.payload["code"] == "invalid_request"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_rejects_path_like_session_ids(self, tmp_path):
        data_dir = _write_mock_data_dir(tmp_path)
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _send_frame(
                proc,
                "hello",
                session_id="../escape",
                thread_id="t-sub",
                request_id="req-hello",
            )
            assert (await _read_frame(proc)).type == "hello_ok"

            await _send_frame(
                proc,
                "session.open",
                session_id="../escape",
                thread_id="t-sub",
                request_id="req-open",
            )
            error = await _read_frame(proc)
            assert error.type == "error"
            assert error.request_id == "req-open"
            assert error.payload["code"] == "session_open_failed"
            assert "session_id" in error.payload["message"]
            assert not (tmp_path / "escape").exists()
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_subprocess_roundtrip_with_mock_provider(self, tmp_path):
        data_dir = _write_mock_data_dir(tmp_path)
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _send_frame(
                proc,
                "hello",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-hello",
            )
            hello = await _read_frame(proc)
            assert hello.type == "hello_ok"
            assert hello.session_id == "s-sub"
            assert hello.thread_id == "t-sub"
            assert hello.request_id == "req-hello"

            await _send_frame(
                proc,
                "session.open",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-open",
            )
            ready = await _read_frame(proc)
            assert ready.type == "session_ready"
            assert ready.session_id == "s-sub"
            assert ready.thread_id == "t-sub"
            assert ready.request_id == "req-open"

            await _send_frame(
                proc,
                "user.message",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-user-1",
                payload={"content": "hello"},
            )
            frames = []
            while True:
                frame = await _read_frame(proc)
                frames.append(frame)
                if frame.type == "turn_finished":
                    break

            assert [f.type for f in frames] == [
                "turn_started",
                "assistant_message",
                "turn_finished",
            ]
            assistant = next(f for f in frames if f.type == "assistant_message")
            assert assistant.payload["content"] == "hello from subprocess"
            assert all(f.session_id == "s-sub" for f in frames)
            assert all(f.thread_id == "t-sub" for f in frames)
            assert all(f.request_id == "req-user-1" for f in frames)

            await _send_frame(
                proc,
                "shutdown",
                session_id="s-sub",
                thread_id="t-sub",
                request_id="req-shutdown",
            )
            shutdown = await _read_frame(proc)
            assert shutdown.type == "shutdown_ok"
            assert shutdown.request_id == "req-shutdown"

            state_path = data_dir / "sessions" / "s-sub" / "state" / "state.yaml"
            state = yaml.safe_load(state_path.read_text(encoding="utf-8"))
            assert state["status"] == "closed"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_streams_interaction_tool_events(self, tmp_path):
        data_dir = _write_mock_data_dir(
            tmp_path,
            tools=["send_message", "ask_user"],
            mock_responses=[
                {
                    "content": "notifying",
                    "tool_calls": [
                        {
                            "name": "send_message",
                            "args": {"message": "heads up"},
                            "id": "call_notice",
                        },
                        {
                            "name": "ask_user",
                            "args": {"question": "Proceed?", "options": ["yes", "no"]},
                            "id": "call_ask",
                        },
                    ],
                },
                {"content": "answer received"},
            ],
        )
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-events", thread_id="t-events")
            await _send_frame(
                proc,
                "user.message",
                session_id="s-events",
                thread_id="t-events",
                request_id="req-events",
                payload={"content": "trigger"},
            )
            frames = []
            answered = False
            while True:
                frame = await _read_frame(proc)
                frames.append(frame)
                if frame.type == "user_input_required" and not answered:
                    await _send_frame(
                        proc,
                        "user.input",
                        session_id="s-events",
                        thread_id="t-events",
                        request_id="req-answer",
                        payload={
                            "request_id": frame.payload["request_id"],
                            "answer": "yes",
                        },
                    )
                    answered = True
                if frame.type == "turn_finished":
                    break

            frame_types = [frame.type for frame in frames]
            assert "client_message" in frame_types
            assert "user_input_required" in frame_types
            assert "user_input_recorded" in frame_types
            assert frame_types.count("assistant_message") == 2
            assert all(frame.request_id == "req-events" for frame in frames)
            notice = next(frame for frame in frames if frame.type == "client_message")
            question = next(frame for frame in frames if frame.type == "user_input_required")
            assert notice.payload["message"] == "heads up"
            assert question.payload["question"] == "Proceed?"
            assert question.payload["request_id"] == "user_input:call_ask"
            assert question.payload["source"] == "ask_user"
            assert question.payload["resume_supported"] is False
            tool_result = next(
                frame
                for frame in frames
                if frame.type == "tool_result"
                and frame.payload["tool_call_id"] == "call_ask"
            )
            assert "User answered: yes" in tool_result.payload["content"]

            state_path = data_dir / "sessions" / "s-events" / "state" / "state.yaml"
            state = yaml.safe_load(state_path.read_text(encoding="utf-8"))
            assert state["pending_interactions"] == []
            recorded = next(frame for frame in frames if frame.type == "user_input_recorded")
            assert recorded.type == "user_input_recorded"
            assert recorded.request_id == "req-events"
            assert recorded.payload["request_id"] == "user_input:call_ask"
            assert recorded.payload["resume_supported"] is False
            assert recorded.payload["status"] == "answered"
            assert recorded.payload["pending_interactions"] == []
            events_path = data_dir / "sessions" / "s-events" / "state" / "events.jsonl"
            events = [json.loads(line) for line in events_path.read_text().splitlines()]
            response_event = next(event for event in events if event["type"] == "user_input_response")
            assert response_event["payload"]["request_type"] == "user_input_required"
            assert response_event["payload"]["request_source"] == "ask_user"
            assert response_event["payload"]["request_payload"]["question"] == "Proceed?"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_live_permission_allow_continues_tool_call(self, tmp_path):
        data_dir = _write_mock_data_dir(
            tmp_path,
            tools=["send_message"],
            mock_responses=[
                {
                    "content": "notice",
                    "tool_calls": [
                        {
                            "name": "send_message",
                            "args": {"message": "needs approval"},
                            "id": "call_perm",
                        }
                    ],
                },
                {"content": "done"},
            ],
            permissions=(
                "permissions:\n"
                "  ask:\n"
                "    - tool: send_message\n"
            ),
        )
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-perm", thread_id="t-perm")
            await _send_frame(
                proc,
                "user.message",
                session_id="s-perm",
                thread_id="t-perm",
                request_id="req-perm",
                payload={"content": "trigger"},
            )
            frames = []
            approved = False
            while True:
                frame = await _read_frame(proc)
                frames.append(frame)
                if frame.type == "permission_request" and not approved:
                    await _send_frame(
                        proc,
                        "permission.response",
                        session_id="s-perm",
                        thread_id="t-perm",
                        request_id="req-perm-response",
                        payload={
                            "request_id": frame.payload["request_id"],
                            "decision": "allow",
                        },
                    )
                    approved = True
                if frame.type == "turn_finished":
                    break

            permission = next(frame for frame in frames if frame.type == "permission_request")
            assert permission.payload["request_id"] == "permission:call_perm"
            state_path = data_dir / "sessions" / "s-perm" / "state" / "state.yaml"
            state = yaml.safe_load(state_path.read_text(encoding="utf-8"))
            assert state["pending_interactions"] == []
            recorded = next(frame for frame in frames if frame.type == "permission_response_recorded")
            assert recorded.type == "permission_response_recorded"
            assert recorded.request_id == "req-perm"
            assert recorded.payload["decision"] == "allow"
            assert recorded.payload["status"] == "answered"
            assert recorded.payload["pending_interactions"] == []
            assert any(frame.type == "client_message" for frame in frames)
            assert [frame.type for frame in frames].count("assistant_message") == 2
            events_path = data_dir / "sessions" / "s-perm" / "state" / "events.jsonl"
            events = [json.loads(line) for line in events_path.read_text().splitlines()]
            response_event = next(event for event in events if event["type"] == "permission_response")
            assert response_event["payload"]["request_type"] == "permission_request"
            assert response_event["payload"]["request_source"] == "permission_system"
            assert response_event["payload"]["request_payload"]["tool_call"]["id"] == "call_perm"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_live_sandbox_allow_continues_tool_call(self, tmp_path):
        data_dir = _write_mock_data_dir(
            tmp_path,
            tools=["filesystem_read"],
            mock_responses=[
                {
                    "content": "read gated",
                    "tool_calls": [
                        {
                            "name": "filesystem_read",
                            "args": {"path": "gated/file.txt"},
                            "id": "call_sandbox",
                        }
                    ],
                },
                {"content": "done"},
            ],
            permissions=(
                "permissions:\n"
                "  allow:\n"
                "    - tool: filesystem_read\n"
            ),
            sandbox=(
                "sandbox:\n"
                "  enabled: true\n"
                "  resources:\n"
                "    - path: \"{{ workspace }}/gated\"\n"
                "      access: ask\n"
            ),
        )
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-sandbox", thread_id="t-sandbox")
            target = data_dir / "sessions" / "s-sandbox" / "workspace" / "gated" / "file.txt"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text("secret content\n", encoding="utf-8")

            await _send_frame(
                proc,
                "user.message",
                session_id="s-sandbox",
                thread_id="t-sandbox",
                request_id="req-sandbox",
                payload={"content": "trigger"},
            )
            frames = []
            approved = False
            while True:
                frame = await _read_frame(proc)
                frames.append(frame)
                if frame.type == "permission_request" and not approved:
                    assert frame.payload["source"] == "sandbox"
                    await _send_frame(
                        proc,
                        "permission.response",
                        session_id="s-sandbox",
                        thread_id="t-sandbox",
                        request_id="req-sandbox-response",
                        payload={
                            "request_id": frame.payload["request_id"],
                            "decision": "allow",
                        },
                    )
                    approved = True
                if frame.type == "turn_finished":
                    break

            result = next(frame for frame in frames if frame.type == "tool_result")
            assert result.payload["status"] == "success"
            assert "secret content" in result.payload["content"]
            recorded = next(frame for frame in frames if frame.type == "permission_response_recorded")
            assert recorded.payload["decision"] == "allow"
            assert recorded.payload["scope"] == "once"
            events_path = data_dir / "sessions" / "s-sandbox" / "state" / "events.jsonl"
            events = [json.loads(line) for line in events_path.read_text().splitlines()]
            response_event = next(event for event in events if event["type"] == "permission_response")
            assert response_event["payload"]["request_source"] == "sandbox"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_permission_response_session_scope_persists_policy(self, tmp_path):
        data_dir = _write_mock_data_dir(
            tmp_path,
            tools=["send_message"],
            mock_responses=[
                {
                    "content": "notice",
                    "tool_calls": [
                        {
                            "name": "send_message",
                            "args": {"message": "remember this"},
                            "id": "call_perm",
                        }
                    ],
                },
                {"content": "done"},
            ],
            permissions=(
                "permissions:\n"
                "  ask:\n"
                "    - tool: send_message\n"
            ),
        )
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-policy", thread_id="t-policy")
            await _send_frame(
                proc,
                "user.message",
                session_id="s-policy",
                thread_id="t-policy",
                request_id="req-policy",
                payload={"content": "trigger"},
            )
            while True:
                frame = await _read_frame(proc)
                if frame.type == "permission_request":
                    await _send_frame(
                        proc,
                        "permission.response",
                        session_id="s-policy",
                        thread_id="t-policy",
                        request_id="req-policy-response",
                        payload={
                            "request_id": frame.payload["request_id"],
                            "decision": "allow",
                            "scope": "session",
                        },
                    )
                if frame.type == "turn_finished":
                    break

            policy_path = data_dir / "sessions" / "s-policy" / "policy.yaml"
            policy = yaml.safe_load(policy_path.read_text(encoding="utf-8"))
            assert policy["permissions"]["allow"][0]["tool"] == "send_message"
            assert policy["permissions"]["allow"][0]["params"]["message"] == "remember\\ this"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_permission_response_always_scope_persists_personality(self, tmp_path):
        data_dir = _write_mock_data_dir(
            tmp_path,
            tools=["send_message"],
            mock_responses=[
                {
                    "content": "notice",
                    "tool_calls": [
                        {
                            "name": "send_message",
                            "args": {"message": "always remember"},
                            "id": "call_perm",
                        }
                    ],
                },
                {"content": "done"},
            ],
            permissions=(
                "permissions:\n"
                "  ask:\n"
                "    - tool: send_message\n"
            ),
        )
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-always", thread_id="t-always")
            await _send_frame(
                proc,
                "user.message",
                session_id="s-always",
                thread_id="t-always",
                request_id="req-always",
                payload={"content": "trigger"},
            )
            while True:
                frame = await _read_frame(proc)
                if frame.type == "permission_request":
                    await _send_frame(
                        proc,
                        "permission.response",
                        session_id="s-always",
                        thread_id="t-always",
                        request_id="req-always-response",
                        payload={
                            "request_id": frame.payload["request_id"],
                            "decision": "allow",
                            "scope": "always",
                        },
                    )
                if frame.type == "turn_finished":
                    break

            personality_path = data_dir / "personalities" / "default" / "personality.yaml"
            personality = yaml.safe_load(personality_path.read_text(encoding="utf-8"))
            assert personality["permissions"]["allow"][0]["tool"] == "send_message"
            assert personality["permissions"]["allow"][0]["params"]["message"] == "always\\ remember"
        finally:
            await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_stops_live_ask_when_client_disconnects(self, tmp_path):
        data_dir = _write_mock_data_dir(
            tmp_path,
            tools=["ask_user"],
            mock_responses=[
                {
                    "content": "ask",
                    "tool_calls": [
                        {
                            "name": "ask_user",
                            "args": {"question": "Proceed?"},
                            "id": "call_ask",
                        }
                    ],
                },
                {"content": "should not run"},
            ],
        )
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-disconnect", thread_id="t-disconnect")
            await _send_frame(
                proc,
                "user.message",
                session_id="s-disconnect",
                thread_id="t-disconnect",
                request_id="req-disconnect",
                payload={"content": "trigger"},
            )
            frames = []
            while True:
                frame = await _read_frame(proc)
                frames.append(frame)
                if frame.type == "user_input_required":
                    await _disconnect_process_client(proc)
                    break

            await _wait_process_exit_or_stop(proc, timeout=10)
            await _drain_process_pipes(proc)
            assert [frame.type for frame in frames].count("assistant_message") == 1
            state_path = data_dir / "sessions" / "s-disconnect" / "state" / "state.yaml"
            state = yaml.safe_load(state_path.read_text(encoding="utf-8"))
            assert state["status"] == "interrupted"
            assert state["pending_interactions"] == []
            events_path = data_dir / "sessions" / "s-disconnect" / "state" / "events.jsonl"
            events = [json.loads(line) for line in events_path.read_text().splitlines()]
            cancelled = next(event for event in events if event["type"] == "user_input_cancelled")
            assert cancelled["payload"]["status"] == "disconnected"
        finally:
            if proc.returncode is None:
                await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_stops_live_permission_when_client_disconnects(self, tmp_path):
        data_dir = _write_mock_data_dir(
            tmp_path,
            tools=["send_message"],
            mock_responses=[
                {
                    "content": "notice",
                    "tool_calls": [
                        {
                            "name": "send_message",
                            "args": {"message": "needs approval"},
                            "id": "call_perm",
                        }
                    ],
                },
                {"content": "should not run"},
            ],
            permissions=(
                "permissions:\n"
                "  ask:\n"
                "    - tool: send_message\n"
            ),
        )
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-perm-drop", thread_id="t-perm-drop")
            await _send_frame(
                proc,
                "user.message",
                session_id="s-perm-drop",
                thread_id="t-perm-drop",
                request_id="req-perm-drop",
                payload={"content": "trigger"},
            )
            frames = []
            while True:
                frame = await _read_frame(proc)
                frames.append(frame)
                if frame.type == "permission_request":
                    await _disconnect_process_client(proc)
                    break

            await _wait_process_exit_or_stop(proc, timeout=10)
            await _drain_process_pipes(proc)
            assert [frame.type for frame in frames].count("assistant_message") == 1
            assert not any(frame.type == "client_message" for frame in frames)
            state_path = data_dir / "sessions" / "s-perm-drop" / "state" / "state.yaml"
            state = yaml.safe_load(state_path.read_text(encoding="utf-8"))
            assert state["status"] == "interrupted"
            assert state["pending_interactions"] == []
            events_path = data_dir / "sessions" / "s-perm-drop" / "state" / "events.jsonl"
            events = [json.loads(line) for line in events_path.read_text().splitlines()]
            cancelled = next(event for event in events if event["type"] == "permission_cancelled")
            assert cancelled["payload"]["status"] == "disconnected"
        finally:
            if proc.returncode is None:
                await _stop_process(proc)

    @pytest.mark.asyncio
    async def test_server_rejects_unknown_interaction_response(self, tmp_path):
        data_dir = _write_mock_data_dir(tmp_path)
        env = {
            **os.environ,
            "PYTHONPATH": _subprocess_pythonpath(),
        }

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            "-m",
            "xbotv2",
            "--data-dir",
            str(data_dir),
            "--provider",
            "mock",
            "--mode",
            "server",
            "--no-plugins",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        try:
            await _open_session(proc, session_id="s-missing", thread_id="t-missing")
            await _send_frame(
                proc,
                "user.input",
                session_id="s-missing",
                thread_id="t-missing",
                request_id="req-missing",
                payload={"request_id": "user_input:missing", "answer": "yes"},
            )
            error = await _read_frame(proc)
            assert error.type == "error"
            assert error.payload["code"] == "invalid_request"
            assert "No pending user input request" in error.payload["message"]

            events_path = data_dir / "sessions" / "s-missing" / "state" / "events.jsonl"
            events = [json.loads(line) for line in events_path.read_text().splitlines()]
            assert not any(event["type"] == "user_input_response" for event in events)
        finally:
            await _stop_process(proc)


# TestTerminalSessionSubprocess (stdio subprocess roundtrips) was removed in
# the v2.2 doc revision (HTTP-only). The same coverage now lives in
# tests/integration/test_http_transport.py. The remaining
# TestRuntimeServerSubprocess tests still drive the stdio server via
# subprocess to exercise the engine's behavior end-to-end, since the
# stdio transport (xbotv2/protocol/server.py) is kept in the source tree
# as a legacy alternative for engine integration testing.


async def _open_session(proc, *, session_id: str, thread_id: str) -> None:
    await _send_frame(
        proc,
        "hello",
        session_id=session_id,
        thread_id=thread_id,
        request_id="req-hello",
    )
    assert (await _read_frame(proc)).type == "hello_ok"
    await _send_frame(
        proc,
        "session.open",
        session_id=session_id,
        thread_id=thread_id,
        request_id="req-open",
    )
    assert (await _read_frame(proc)).type == "session_ready"


def _write_mock_data_dir(
    tmp_path,
    *,
    tools: list[str] | None = None,
    mock_responses: list[dict] | None = None,
    permissions: str | None = None,
    sandbox: str | None = None,
):
    data_dir = tmp_path / "data"
    (data_dir / "config").mkdir(parents=True)
    (data_dir / "personalities" / "default").mkdir(parents=True)
    (data_dir / "config" / "user.yaml").write_text("user_id: test\nuser_name: Tester\n")
    mock_responses = mock_responses or [{"content": "hello from subprocess"}]
    (data_dir / "config" / "provider.yaml").write_text(
        "mock:\n"
        "  provider: mock\n"
        f"  mock_responses: {json.dumps(mock_responses)}\n"
    )
    tool_yaml = (
        "tools:\n" + "".join(f"  - {tool_name}\n" for tool_name in tools)
        if tools
        else "tools: []\n"
    )
    permissions_yaml = permissions or (
        "permissions:\n"
        "  allow:\n"
        "    - tool: send_message\n"
        "    - tool: ask_user\n"
    )
    sandbox_yaml = sandbox or (
        "sandbox:\n"
        "  enabled: false\n"
    )
    (data_dir / "personalities" / "default" / "personality.yaml").write_text(
        "agent_name: TestBot\n"
        "agent_role: Test runtime\n"
        f"{tool_yaml}"
        f"{permissions_yaml}"
        f"{sandbox_yaml}"
    )
    return data_dir


async def _send_frame(
    proc,
    frame_type: str,
    *,
    session_id: str,
    thread_id: str,
    request_id: str = "",
    payload: dict | None = None,
):
    frame = ProtocolFrame(
        seq=1,
        direction="client_to_server",
        type=frame_type,
        session_id=session_id,
        thread_id=thread_id,
        request_id=request_id,
        payload=payload or {},
    )
    proc.stdin.write(frame.to_json_line().encode("utf-8"))
    await proc.stdin.drain()


async def _read_frame(proc) -> ProtocolFrame:
    line = await asyncio.wait_for(proc.stdout.readline(), timeout=5)
    if not line:
        stderr = await proc.stderr.read()
        raise AssertionError(f"Server exited before frame. stderr={stderr.decode('utf-8')}")
    return frame_from_json(line.decode("utf-8"))


async def _stop_process(proc) -> None:
    if proc.returncode is None:
        proc.terminate()
        try:
            await asyncio.wait_for(proc.wait(), timeout=5)
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
    await _drain_process_pipes(proc)


async def _wait_process_exit_or_stop(proc, *, timeout: float) -> None:
    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout
    while proc.returncode is None and loop.time() < deadline:
        await asyncio.sleep(0.05)
    if proc.returncode is None:
        await _stop_process(proc)
        raise asyncio.TimeoutError


async def _disconnect_process_client(proc) -> None:
    if proc.stdin is not None and not proc.stdin.is_closing():
        proc.stdin.close()
        await proc.stdin.wait_closed()
    stdout_transport = getattr(proc.stdout, "_transport", None)
    if stdout_transport is not None:
        stdout_transport.close()


async def _drain_process_pipes(proc) -> None:
    for pipe in (proc.stdout, proc.stderr):
        if pipe is None:
            continue
        try:
            await asyncio.wait_for(pipe.read(), timeout=1)
        except (asyncio.TimeoutError, ValueError):
            continue


def _subprocess_pythonpath() -> str:
    repo_root = os.getcwd()
    paths = [str(os.path.join(repo_root, "XBotv2")), repo_root]
    existing = os.environ.get("PYTHONPATH")
    if existing:
        paths.append(existing)
    return os.pathsep.join(paths)
