"""Shared contracts for XBotv2.

Plugins and applications import capability-neutral contracts from this
package. Plugin-owned declarations are exported by their owning package roots;
engine internals remain implementation details.
"""

from XBotv2.core.artifacts import ArtifactKind, ArtifactRef, ArtifactStorePort
from XBotv2.core.history import ConversationHistory, HistorySink
from XBotv2.core.messages import (
    AssistantMessage,
    CompactionSummaryMessage,
    ConversationMessage,
    HumanInputMessage,
    ImagePart,
    ReasoningPart,
    RuntimeNoticeMessage,
    TextPart,
    ToolMessage,
)
from XBotv2.core.stream import (
    ModelCancelled,
    ModelCompleted,
    ModelFailed,
    ModelResponse,
    ModelStreamEvent,
    ToolCallDelta,
    ReasoningDelta,
    TextDelta,
)
from XBotv2.core.domain import (
    AgentExecutionLimits,
    AuxiliaryRequest,
    GenerationMode,
    GenerationSettings,
    MeasurementUnavailable,
    ModelExchange,
    ModelRoute,
    ModelTiming,
    ProviderExtensions,
    ProviderError,
    ProviderErrorCategory,
    ProviderMeasured,
    RequestObservation,
    ResolvedModelSelection,
    ResolvedRuntimeSelection,
    TokenCounters,
    UsageDelta,
    UsageSnapshot,
)
from XBotv2.core.operations import (
    EmptyRequest,
    Operation,
    OperationContext,
    dispatch_operation,
)
from XBotv2.core.paths import RuntimePaths, SessionPaths, ThreadPaths
from XBotv2.core.provider import (
    ProviderAssistant,
    ProviderMessage,
    ProviderSystem,
    ProviderTool,
    ProviderUser,
    ResolvedImagePart,
    ToolSchema,
)
from XBotv2.core.prompts import MESSAGE_FORMAT_KEY, prompt_container, prompt_element
from XBotv2.core.providers import (
    BaseProvider,
    InputModality,
    ProviderCapabilities,
    ProviderFailure,
)
from XBotv2.core.tokens import (
    TokenBudget,
    context_token_limit,
    estimate_messages_tokens,
    estimate_model_request_tokens,
    estimate_request_tokens,
    estimate_text_tokens,
)
from XBotv2.core.tools import (
    CompleteTurn,
    ContinueTurn,
    Tool,
    ToolCall,
    ToolCallRef,
    ToolCancelled,
    ToolDenied,
    ToolError,
    ToolFailed,
    ToolExecution,
    ToolOutput,
    ToolOutcome,
    ToolSucceeded,
    TurnDirective,
    failed_text,
    succeeded_text,
    text_output,
)
from XBotv2.core.variables import RuntimeVariables

__all__ = [
    "ArtifactRef",
    "ArtifactKind",
    "ArtifactStorePort",
    "AssistantMessage",
    "CompactionSummaryMessage",
    "ConversationMessage",
    "ConversationHistory",
    "EmptyRequest",
    "Operation",
    "OperationContext",
    "ImagePart",
    "InputModality",
    "HistorySink",
    "MESSAGE_FORMAT_KEY",
    "ModelResponse",
    "ModelStreamEvent",
    "ModelCompleted",
    "ModelFailed",
    "ModelCancelled",
    "ToolCallDelta",
    "TextDelta",
    "ReasoningDelta",
    "BaseProvider",
    "ProviderError",
    "ProviderErrorCategory",
    "ProviderFailure",
    "ProviderCapabilities",
    "ReasoningPart",
    "RuntimeNoticeMessage",
    "RuntimePaths",
    "RuntimeVariables",
    "SessionPaths",
    "TextPart",
    "ThreadPaths",
    "Tool",
    "ToolCall",
    "CompleteTurn",
    "ContinueTurn",
    "ToolError",
    "ToolCallRef",
    "ToolCancelled",
    "ToolDenied",
    "ToolFailed",
    "ToolExecution",
    "ToolOutput",
    "ToolOutcome",
    "ToolSucceeded",
    "TurnDirective",
    "failed_text",
    "succeeded_text",
    "text_output",
    "ToolMessage",
    "AgentExecutionLimits",
    "AuxiliaryRequest",
    "GenerationMode",
    "GenerationSettings",
    "MeasurementUnavailable",
    "ModelExchange",
    "ModelRoute",
    "ModelTiming",
    "ProviderExtensions",
    "ProviderMeasured",
    "RequestObservation",
    "ResolvedModelSelection",
    "ResolvedRuntimeSelection",
    "TokenCounters",
    "UsageDelta",
    "UsageSnapshot",
    "TokenBudget",
    "context_token_limit",
    "estimate_messages_tokens",
    "estimate_model_request_tokens",
    "dispatch_operation",
    "estimate_request_tokens",
    "estimate_text_tokens",
    "prompt_container",
    "prompt_element",
    "ProviderAssistant",
    "ProviderMessage",
    "ProviderSystem",
    "ProviderTool",
    "ProviderUser",
    "ResolvedImagePart",
    "ToolSchema",
]
