"""Public declarations for session identity and runtime management."""

from XBotv2.session.contracts import (
    AttachmentInput,
    ArtifactPayload,
    HistoryMutation,
    ImageInput,
    InteractionReceipt,
    InterruptResult,
    OpenedSession,
    OpenSession,
    OpenThread,
    PendingInputData,
    PendingInputUpdate,
    RegenerateMessage,
    SendMessage,
    SESSION_RESOURCE_CHANGED,
    SESSION_RESOURCE_REMOVED,
    SessionDescriptor,
    SessionExists,
    SessionInfo,
    SessionMode,
    SessionNotFound,
    SessionResourceChanged,
    SessionResourceRemoved,
    SessionSummary,
    ThreadNotActive,
    ThreadSummary,
    new_session_id,
)

__all__ = [
    "AgentApplicationFactory",
    "AgentApplicationOptions",
    "AgentConfiguredData",
    "AttachmentInput",
    "ArtifactPayload",
    "CloseResponse",
    "DeleteSessionResponse",
    "ForkResponse",
    "HISTORY_CHANGED",
    "HistoryChanged",
    "HistoryMutationResponse",
    "HistoryUpdatedData",
    "ImageInput",
    "InterruptResponse",
    "MessageData",
    "MessageRequest",
    "PREPARE_FORK",
    "PrepareFork",
    "OpenSessionRequest",
    "OpenSessionResponse",
    "OpenThreadRequest",
    "PendingInputData",
    "PendingInputListResponse",
    "PendingInputUpdateRequest",
    "RegenerateMessage",
    "RegenerateRequest",
    "SessionsPort",
    "SessionHistoryItem",
    "SessionListResponse",
    "SessionEventType",
    "SessionMode",
    "SessionSummary",
    "SessionPort",
    "SessionStatus",
    "HistoryMutation",
    "InteractionReceipt",
    "InterruptResult",
    "OpenedSession",
    "OpenSession",
    "OpenThread",
    "PendingInputUpdate",
    "SendMessage",
    "SESSION_RESOURCE_CHANGED",
    "SESSION_RESOURCE_REMOVED",
    "SessionExists",
    "SessionDescriptor",
    "SessionInfo",
    "SessionNotFound",
    "SessionResourceChanged",
    "SessionResourceRemoved",
    "ThreadNotActive",
    "ThreadListResponse",
    "ThreadMessagesResponse",
    "ThreadSummary",
    "new_session_id",
    "UndoRequest",
    "build_session_commands",
    "session_event",
    "session_error_event",
]

_COMMAND_EXPORTS = {"build_session_commands"}
_CONTRACT_EXPORTS = {
    "AgentApplicationFactory",
    "AgentApplicationOptions",
    "HISTORY_CHANGED",
    "HistoryChanged",
    "PREPARE_FORK",
    "PrepareFork",
    "SessionStatus",
    "SessionDescriptor",
    "SESSION_RESOURCE_CHANGED",
    "SESSION_RESOURCE_REMOVED",
    "SessionResourceChanged",
    "SessionResourceRemoved",
    "new_session_id",
}
_CONTRACT_EXPORTS.update({"SessionPort", "SessionsPort"})

_PROTOCOL_EXPORTS = {
    "AgentConfiguredData",
    "AttachmentInput",
    "CloseResponse",
    "DeleteSessionResponse",
    "ForkResponse",
    "HistoryMutationResponse",
    "HistoryUpdatedData",
    "ImageInput",
    "InterruptResponse",
    "MessageData",
    "MessageRequest",
    "OpenSessionRequest",
    "OpenSessionResponse",
    "OpenThreadRequest",
    "PendingInputData",
    "PendingInputListResponse",
    "PendingInputUpdateRequest",
    "RegenerateRequest",
    "SessionEventType",
    "SessionHistoryItem",
    "SessionListResponse",
    "SessionSummary",
    "ThreadListResponse",
    "ThreadMessagesResponse",
    "ThreadSummary",
    "UndoRequest",
    "session_error_event",
    "session_event",
}


def __getattr__(name: str) -> object:
    if name in _COMMAND_EXPORTS:
        from XBotv2.session import commands as declarations
    elif name in _CONTRACT_EXPORTS:
        from XBotv2.session import contracts as declarations
    elif name in _PROTOCOL_EXPORTS:
        from XBotv2.session import protocol as declarations
    else:
        raise AttributeError(name)

    return getattr(declarations, name)
