"""Public declarations for the background-jobs plugin."""

from XBotv2.jobs.contracts import (
    JOB_COMPLETED,
    JOB_UPDATED,
    LIST_JOBS,
    STOP_ALL_JOBS,
    STOP_JOB,
    CancelResult,
    CancelledBeforeStart,
    CancelledRunning,
    FailedBeforeStart,
    FailedRunning,
    Job,
    JobCatalog,
    JobError,
    JobId,
    JobIdentity,
    JobNotFound,
    JobRegistryClosed,
    JobRunner,
    JobsCommandPort,
    JobsConfig,
    JobsPort,
    JobSpec,
    JobState,
    JobStateName,
    JobView,
    MAX_SUMMARY_CHARS,
    OutputPage,
    Queued,
    Running,
    StopJob,
    StoppedJobs,
    Succeeded,
    WaitMode,
    WaitResult,
    parse_job_status,
)
from XBotv2.jobs.protocol import (
    JobCompletedEvent,
    JobListResponse,
    JobStopResponse,
    JobUpdatedEvent,
    job_completed_event,
    job_updated_event,
)

__all__ = [
    "CancelResult", "CancelledBeforeStart", "CancelledRunning", "FailedBeforeStart",
    "FailedRunning", "Job", "JobCatalog", "JobCompletedEvent", "JobError", "JobId",
    "JobIdentity", "JobListResponse", "JobNotFound", "JobRegistryClosed",
    "JobRunner", "JobsCommandPort",
    "JobsConfig", "JobsPort", "JobSpec", "JobState", "JobStateName", "JobStopResponse",
    "JobUpdatedEvent", "JobView", "JOB_COMPLETED", "JOB_UPDATED", "LIST_JOBS",
    "MAX_SUMMARY_CHARS", "OutputPage", "Queued", "Running", "STOP_ALL_JOBS",
    "STOP_JOB", "StopJob", "StoppedJobs", "Succeeded", "WaitMode",
    "WaitResult", "job_completed_event", "job_updated_event", "parse_job_status",
]
